[workspace]
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
authors = ["June Bergeron <jrbergeron823@gmail.com>"]
edition = "2021"

[workspace.dependencies]
jam = { path = "crates/jam" }
